// Generated by CoffeeScript 1.4.0
(function() {
  var checkStyle, checks, esprima, estraverse, formatErrors, parseOptions, _;

  esprima = require('esprima');

  estraverse = require('estraverse');

  _ = require('underscore');

  checks = {
    VariableDeclaration: function(node) {
      var errors;
      errors = _.map(node.declarations, function(decl) {
        var err;
        if (decl.id.name.indexOf('_') >= 0) {
          return err = {
            location: decl.loc,
            message: 'Use camelCase for variable names, not hacker_style.'
          };
        }
      });
      return _.compact(errors);
    }
  };

  checkStyle = function(code, filename) {
    var ast, errors;
    ast = esprima.parse(code, parseOptions);
    errors = [];
    estraverse.traverse(ast, {
      enter: function(node, parent) {
        if (checks[node.type]) {
          return errors = errors.concat(checks[node.type](node, parent));
        }
      }
    });
    return formatErrors(code, errors, filename);
  };

  formatErrors = function(code, errors, filename) {
    return _.map(errors, function(e) {
      var loc, prefix;
      loc = e.location.start;
      prefix = (typeof filename === "function" ? filename("" + filename + ":" + loc.line + ":" + loc.column) : void 0) ? void 0 : "Line " + loc.line + ", column " + loc.column;
      return "" + prefix + ": " + e.message;
    });
  };

  parseOptions = {
    loc: true,
    range: true
  };

  console.log(checkStyle("var foo = bar;\nvar this_is_bad = 3;\nfunction blah() {\n  return function x() { var oops_another_one; }\n}"));

}).call(this);
