// Generated by CoffeeScript 1.4.0
(function() {
  var esprima, estraverse, idgrep, parseOptions;

  esprima = require('esprima');

  estraverse = require('estraverse');

  idgrep = function(pattern, code, filename) {
    var ast, lines;
    lines = code.split('\n');
    ast = esprima.parse(code, parseOptions);
    estraverse.traverse(ast, {
      enter: function(node, parent) {
        var line, loc;
        if (node.type === 'Identifier' && node.name.indexOf(pattern) >= 0) {
          loc = node.loc.start;
          line = loc.line - 1;
          console.log("" + line + ":" + loc.column + ": " + lines[line]);
        }
      }
    });
  };

  parseOptions = {
    loc: true,
    range: true
  };

  idgrep('hack', "// This is a hack!\nfunction hacky_function() {\n  var hack = 3;\n  return 'hacky string';\n}");

}).call(this);
